- custom/cve5/conf.js
This doesn't actually do anything - actually rejecting the CVE still must be done manually by the Security team
> Allow CVE's to be in a 'REJECTED' state

- .asf.yaml
Instead of security@apache.org
See also INFRA-24118
> Send main commit notifications to private@security

- default/cve5/script.js
When you type a URL into the WYSIWYG editor, it gets converted to a link automatically. However, when it is then converted to plain text, htmltoText produces the URL twice: once as the 'link text' and once as the link itself.
This change makes sure that if the link text is identical to the link itself, it is not repeated.
> Avoid repeating a URL in the HTML to text conversion

- custom/cve5/conf.js
By correctly specifying the path to the 'oneOf' box.
This was reviewed earlier in #51, but that was still targeting the old branch. Tested locally.
> Correctly show red border when severity level is missing

- README.md
- app.js
`secure` to make sure it is not sent over non-https connections, and `httpOnly` to make sure it cannot be stolen in an XSS attack.
> Create session cookie with secure flags

- default/cve5/script.js
Still allow a double newline, but remove beyond that. Should improve all notification emails. Tested with a recent comment.
Fixes #84
> Avoid excessive newlines in HTML-to-text conversion

- custom/cve5/conf.js
Make sure they are .apache.org mailinglists, and not to include announce@apache.org or oss-security@lists.openwall.com there
Fixes #67
> Validate mailinglists to notify

- custom/cve5/conf.js
To be able to set the 'unsupported when assigned' tag, https://www.cve.org/Resources/General/End-of-Life-EOL-Assignment-Process.pdf
> Enable 'tags' field

- routes/doc.js
- routes/onedoc.js
Cause: while refactoring doc.js in V1.0.0, one of the variables was global, which meant it pointed to the last document collection. Thats where all the document change histories went instead of the corresponding collection.
Cherry-picked from 5994b27ad4811d28c0aa5a4800842b3d93b7bad6 and fixed conflicts.
Verified in the database that:
* cve_histories does not contain entries that belong in cve5_histories
* nvd_histories contains entries for 4 CVE's that belong in cve_histories
* all other entries in nvd_histories belong in cve5_histories
Tested locally that this PR makes CVE5 histories disappear, and then reappear when I copy the entries from nvd_histories to cve5_histories.
I propose we treat this migration as follows:
* Review and merge this PR
* Deploy to vulnogram test environment
* …
> Fix Histories in wrong collection

- custom/cve5/conf.js
- default/cve5/cvelist.pug
This actionable information is currently often missed in our descriptions.
https://www.openwall.com/lists/oss-security/2023/01/31/7
https://www.openwall.com/lists/oss-security/2022/10/12/2
https://www.openwall.com/lists/oss-security/2022/08/26/4
https://www.openwall.com/lists/oss-security/2022/01/25/15
(this is probably because this is obvious to us, since we publish CVE's after releasing the fixed version. That convention is not universal, though, so it is useful to call it out explicitly)
> Recommend explicitly mentioning the fixed version in the description

- custom/asf.js
Reduce the chance of picking 'dev@' for projects that don't have a 'dev@' list.
> Select a default list for the announcement

- custom/cve5/conf.js
So projects aren't tempted to abuse the public references field for this
Fixes #80
> Allow adding internal references

- custom/asf.js
> Expose public CVE4 cves

- public/js/editor.js
A slightly larger diff to upstream, but simplifies the logic and fixes the issue where saving the document with only unrelated changes would cause times to be shifted by the tz offset.
Follow-up on f413752800c2ee1a1c4585711e68a773ca7ec99c
Fixes https://github.com/apache/security-vulnogram/issues/89
> Simplify timeline UTC date logic

- custom/cve5/conf.js
Useful to record for fine-grained artifact identification, as used in the OSV advisory format and by security scanning software.
> Enable fields for ecosystem-specific package names

- public/js/comment.js
Previously (since https://github.com/apache/security-vulnogram/pull/76), we used `htmltoText` to send notification emails in plain text. While that worked, HTML entities would still show up in HTML. Using `domhtml` will also convert the entities.
> Resolve HTML entities in comment notification emails

- custom/cve5/conf.js
Don't show a warning when there's trailing whitespace (seen at https://cveprocess.apache.org:3555/cve5/CVE-2022-47501#editor)
> Fix ASF list validation

- custom/cve5/asfpreload.js
Fixes #121: recovering gracefully from failures actually already worked, but because port 443 on whimsy is currently not responding at all (not even with 'connection refused' or similar) it has a rather long timeout. Let's explicitly abort after 5s.
> 5-second timeout on whimsy requests

- app.js
We don't use any browser-based integrations, so better to restrict this entirely.
> Stricter CORS headers

- custom/cve5/conf.js
The 'defaultStatus' field leads to confusion, with some projects accidentally setting it to 'y' leading to a version range that would consider any version as 'affected'.
Hiding the 'defaultStatus' field will remove the entry from the CVE JSON entirely for new CVEs. This seems OK: the schema says either defaultStatus or a 'versions' section is required[0], and the docs for the versions[1] say "When defaultStatus is itself omitted, it defaults to unknown", which seems reasonable.
[0] https://github.com/CVEProject/cve-schema/blame/master/schema/v5.0/CVE_JSON_5.0_schema.json#L104
[1] https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/docs/versions.md#version-status-decisions
Fixes #118
> Hide 'defaultStatus' field

- app.js
This helps protect against potential XSS attacks. It *seems* to work OK for me locally, but it is possible that it breaks the OAuth login - this is tricky to test because I don't have HTTPS enabled when testing locally.
To test on the deployed test environment after merging and before moving to prod. If this doesn't work 'lax' might be a second-best setting.
> Add `sameSite` option for cookie

- default/cve5/script.js
Avoids a run-time error (though it seems harmless), follow-up on #123
> Avoid export error

- app.js
this is the easiest way be able to 'remember' the CVE you were going to before getting redirected to the login.
follow-up on #132
> loosen cookie sameSite setting

- default/cve5/conf.js
Having a versionType for single versions should be allowed since 2022 (https://github.com/CVEProject/cve-schema/issues/201), and this should fix #141
Manually checked with CVE-2023-49198 that cve.org also accepts this.
Also proposed upstream in https://github.com/Vulnogram/Vulnogram/pull/234
> remove validation that versionType is empty for non-ranges

- custom/cve5/edit.pug
- public/js/editor.js
Previously, when using the 'Send these Emails' button on the 'OSS/ASF Emails' tab, the CVE was saved with the 'CNA_private.emailed' flag enabled, and in parallel the form to trigger the emails was submitted.
This change makes those two actions sequential: first save the CVE (with the 'emailed' flag set to 'yes'), then post the form.
This fixes https://github.com/apache/security-vulnogram/issues/115 , both the fact that an error box was briefly shown, and the fact that sometimes the 'emailed' flag would not get set to 'yes' correctly.
A downside of this issue is that in case of failure to send the emails, the 'emailed' flag will still be set to 'yes'. That seems acceptable to me: I don't think it has happened much, and when it does it's easy enough to reset the flag on the 'Source' tab. …
> send emails after saving the CVE

- custom/cve5/conf.js
As it is automatically consistently prefixed
fixes #145
> Validate the product name is not repeated in the title

- public/css/min.css
making it italic to make it distinct from 'actual' input
fixes #143
before (focus on the version ranges)
after:
/cc @martin-g
> improve input placeholder text contrast

- custom/cve5/conf.js
Because "package name" is a bit ambigious in this
ecosystem, but here 'groupId:artifactId' is meant.
fixes #144
> Validate maven package names contain a ":"

- custom/cve5/conf.js
The NVD has clarified that they highly encourage us to begin providing CWE values that are outside the CWE-1003 to be more granular with our CWE assertions. Should there be clarity concerns or improper negative impacts to our CVMAP assessment results, we can discuss those as they arise and make adjustments to our understandings or processes as needed.
> problemType: autocomplete all CWEs

- custom/cve5/conf.js
To make it clearer that that's what we're using that field for.
> Change 'other' severity rating label to 'ASF severity rating'
